# Databricks notebook source
# DBTITLE 1,Setup
# MAGIC %pip install --upgrade "mlflow[databricks]>=3.1.0" openai
# MAGIC %restart_python

# COMMAND ----------

import mlflow
import time
import mlflow.genai.datasets
from openai import OpenAI
from mlflow.entities import Document
from typing import List, Dict
from mlflow.genai.scorers import (
    RetrievalGroundedness,
    RelevanceToQuery,
    Safety,
    Guidelines,
)

# COMMAND ----------

CATALOG_NAME = 'pedroz_catalog'
SCHEMA_NAME = 'email_conversations'
OUTPUT_TABLE_NAME = 'generated_emails'
EVALUATION_NAME = 'evaluate_musicstore_emails'

sdf = spark.table(f"{CATALOG_NAME}.{SCHEMA_NAME}.{OUTPUT_TABLE_NAME}")
pdf = sdf.toPandas()

# COMMAND ----------

experiment_name = f"/Users/{dbutils.notebook.entry_point.getDbutils().notebook().getContext().userName().get()}/{EVALUATION_NAME}"

mlflow.set_experiment(experiment_name)

# COMMAND ----------

pdf.drop(['conversation_id', 'customer_email', 'sent_at'], axis='columns', inplace=True)
pdf.rename(
  {
    'prompt': 'inputs',
    'email_content': 'outputs'
  },
  axis='columns',
  inplace=True
)
pdf['inputs'] = pdf['inputs'].apply(lambda x: {'query': x})

# COMMAND ----------

display(pdf.head())

# COMMAND ----------

# MAGIC %md
# MAGIC ___
# MAGIC # Evaluation
# MAGIC Here we create an evaluation dataset using some example questions that were submitted to our model as a baseline. If you want to know more about MLFlow's Evaluation Datasets, check out the [documentation] (https://docs.databricks.com/gcp/en/mlflow3/genai/eval-monitor/concepts/eval-datasets).
# MAGIC
# MAGIC After that, we create what are called [Scorers/Judges](https://docs.databricks.com/gcp/en/mlflow3/genai/eval-monitor/concepts/judges/). These are responsible for evaluating the answers provided by our final model.

# COMMAND ----------

# DBTITLE 1,Evaluation
# Save the scorers as a variable so we can re-use them in step 7
email_scorers = [
        RetrievalGroundedness(),  # Checks if email content is grounded in retrieved data
        Guidelines(
            name="follows_instructions",
            guidelines="The generated email must follow the user_instructions in the request.",
        ),
        Guidelines(
            name="effective_communication",
            guidelines="The email should communicate the key message efficiently without being overly brief or losing important context.",
        ),
        Guidelines(
            name="mentions_contact_name",
            guidelines="The email MUST explicitly mention the customer contact's first name (e.g., Alice, Bob, Carol) in the greeting. Generic greetings like 'Hello' or 'Dear Customer' are not acceptable.",
        ),
        Guidelines(
            name="professional_tone",
            guidelines="The email must be in a professional tone.",
        ),
        Guidelines(
            name="includes_product_links",
            guidelines="The email MUST include product recommendations and links so that the customer can easily purchase the recommended products.",
        ),
        RelevanceToQuery(),  # Checks if email addresses the user's request
        Safety(),  # Checks for harmful or inappropriate content
    ]

# Run evaluation with predefined scorers
eval_results = mlflow.genai.evaluate(
    data=pdf, # Needs to be a pandas df, not spark
    scorers=email_scorers,
)

# COMMAND ----------

# MAGIC %md
# MAGIC ___
# MAGIC # Results
# MAGIC To see the results of the evaluation, you can check out the UI for a more visual presentation by clicking the "View evaluation results" button generated by the cell above, or for a more programatic approach, you can search for it using mlflow.search_traces.
# MAGIC
# MAGIC In the UI, it is also very easy to compare two different evaluations (between two distinct models, for instance) to assertain which achieved better results for your tests.

# COMMAND ----------

# DBTITLE 1,Results
eval_traces = mlflow.search_traces(run_id=eval_results.run_id)

# eval_traces is a Pandas DataFrame that has the evaluated traces.  The column `assessments` includes each scorer's feedback.
eval_traces.head(5)